<div id="ritesh" data-bind="scope:'ritesh-ui-compo'">
    <h2 data-bind="text: title">HI</h2>
</div>
<script type="text/x-magento-init">
    {
        "#ritesh": {
                "Magento_Ui/js/core/app":{
                    "components":{
                        "ritesh-ui-compo":{
                            "component":"Ritesh_UiCompo/js/component", 
                            "title" : "Ritesh Rana uI cOmPoNeNt"
                        }
                    }
                }
            }
    }
</script>
<!-- //DO NOT ADD /web/js  like that on line number 10-->